name: Build macOS project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install xcodes

      - name: Build project
        run: xcodebuild -project _Room/xcode/PROTOTYPE.xcodeproj -configuration Release build
      
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /Users/runner/work/OSXTest/OSXTest/_Room/xcode/build/Release/PROTOTYPE.app
