name: Build macOS project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install xcodes

      - name: Build project
        run: xcodebuild -project _Room/xcode/PROTOTYPE.xcodeproj -configuration Release build

      - name: Print environment variables
        run: env

      - name: Print GITHUB_WORKSPACE
        run: echo ${{GITHUB_WORKSPACE}}
        
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: _Room/xcode/build/Release/PROTOTYPE.app
